FPS = 60

INCOME_PERIOD = FPS
INCOME_BASIC = 10
INCOME_PER_TOWER = 2

DELAY_AFTER_TOWER_DEATH = 60
DELAY_AFTER_TOWER_SPAWN = 0

BUILDING_CD_SHARED = 120

RANGE_LONG = 260.0
RANGE_SHORT = 160.0

TOWER_RADIUS = 20.0
BULLET_RADIUS = 5.0
COLLIDE_DIST = TOWER_RADIUS + BULLET_RADIUS
